source :gemcutter

gem "epic"
gem "f"
gem "haml"
gem "grit"
gem "json"
gem "hpricot"
gem "ruby-growl"
gem "activesupport", "2.3.3", :require => "active_support"
gem "sishen-rtranslate"
gem "progressions-basepath", :require => "basepath"
gem "progressions-g", :require => "g"
gem "timer"
gem "natural_time"
gem "serenity"
gem "string_masker"
gem "ymdt"
gem "ymdp_generator"
gem "ymdp", ">= 0.1.15"
gem "idiom"
gem "rake"