version: 1
sprint_name: Alfa
facebook_api_key: 980c0464131b3ccf2464c88de4207e17
oauth_consumer_key: "dj0yJmk9RTN4ZThldU00T1hkJmQ9WVdrOWQxZFhja3QwTldNbWNHbzlNelUyTWpnek1EWXkmcz1jb25zdW1lcnNlY3JldCZ4PThh"
oauth_consumer_secret: "cf081f3508efb28816eecadbcfb1406447755c41"