version: 1
sprint_name: Alfa
opt_in_destination_email: "optin@humrevsmtp.mail.sk1.yahoo.com"
opt_in_destination_email: "optout@humrevsmtp.mail.sk1.yahoo.com"
# opt_in_destination_email: "jcoleman153@yahoo.com"
# opt_out_destination_email: "jcoleman153@yahoo.com"