sets:
  - abstract
  - animals
  - flowers
  - fun
  - holidaysevents
  - nature
  - patterns
  - sports
themes:
  abstract:
    - construct
    - fantasy_city
    - goth_rose
    - green_circles
    - green_fantasia
    - icy_stripes
    - kaleidoscopes
    - sitting
    - paper_and_seal
    - suburban
  animals:
    - beehive
    - cat_n_mouse
    - goldfish
    - ladybug
    - fetch
    - monkey_bottom
    - nightcat
    - owl
    - panda
    - temptation
  flowers:
    - butterfly_on_daisies
    - daisygreen
    - daisygreen_lavender
    - nouveau_flowers
    - orchids
    - purple_thistle
    - thistle_n_friend
    - thistle_field
    - tulipsgreen
  fun:
    - airplane_top
    - bike
    - fire_ice
    - hills_bottom
    - crowd_surfing
    - lighthouse
    - old_letter
    - pirate_life
    - rainbows
    - silly_birds
    - skulls
    - spring_fantasy
    - toadstools
    - treasure_map
    - undersea
    - wishing_well
  holidaysevents:
    - chinese_new_year
    - christmas_mini
    - city_skyline
    - hall_pumpkins
    - happy_holidays
    - heartplant
    - its_a_boy
    - its_a_girl
    - joy_n_prosperity
    - birthday
    - heart_bubbles
    - party
    - lovecup
    - night_at_bay
    - once_upon_a_time
    - pink_bouquet
    - snow_blue
    - stars_blue
    - travel
    - valentines_day_blue
    - valentines_day_red
    - vote
  nature:
    - bamboo
    - canyon
    - dandelion
    - desert
    - fall
    - green_lizards
    - in_the_clouds
    - lake
    - mountain_top
    - savanna
    - simplistic_nature
    - star_field
    - sunset_on_the_lake
    - valley
  patterns:
    - antique_paper
    - blue_dots
    - blue_scrapbook
    - chinese_motif
    - egyptian_motif
    - fuschia_lattice
    - cardsgold
    - pink_dots
    - stripes_blue
  sports:
    - stitches
    - baseball
    - basketball
    - football
    - football_laces

solid_colors: 
  - "d0d0d0"
  - "855a40"
  - "347d7e"
  - "c49b71"
  - "ff7f00"
  - "2a2a2a"
  - "80ff00"
  - "438059"
  - "bfdfff"
  - "8b8b8b"
  - "ffbfff"
  - "ff9f40"
  - "0080ff"
  - "80c0ff"
  - "033d3d"
  - "b9b9b9"
  - "c00000"
  - "00007f"
  - "482c1b"
  - "8a9b55"
  - "3b5738"
  - "000000"
  - "8080ff"
  - "4040ff"
  - "ff409f"
  - "ffdfbf"
  - "ff80ff"
  - "0000bf"
  - "aa4d4e"
  - "96bdc4"
  - "00ffff"
  - "726284"
  - "1b2c48"
  - "e2f1f4"
  - "a2a2a2"
  - "c0a0b6"
  - "f8dddd"
  - "007f40"
  - "585e82"
  - "d8a5bb"
  - "ff007f"
  - "e0dcaa"
  - "6000bf"
  - "deebf6"
  - "033d21"
  - "ffff40"
  - "e1c4a8"
  - "a8bed1"
  - "7f3f00"
  - "bc6e6e"
  - "ff0000"
  - "b7c296"
  - "ffc0c0"
  - "bfbfff"
  - "dcd1df"
  - "00407f"
  - "e6ebd5"
  - "4a234a"
  - "212143"
  - "441415"
  - "ffbfdf"
  - "a040ff"
  - "9d7292"
  - "609a9f"
  - "ffbf80"
  - "800000"
  - "302449"
  - "c3be71"
  - "936386"
  - "57708f"
  - "80ffff"
  - "5b5b5b"
  - "7f003f"
  - "fdeee0"
  - "737373"
  - "8dae94"
  - "c0ff80"
  - "aea945"
  - "00bfbf"
  - "d8a3a4"
  - "bf00bf"
  - "00ff80"
  - "7f7f00"
  - "bfffff"
  - "407f00"
  - "60bf00"
  - "794a72"
  - "bc6f95"
  - "ff8080"
  - "00bf60"
  - "111111"
  - "0000ff"
  - "668f5a"
  - "d2d1e1"
  - "40007f"
  - "525330"
  - "40ffa0"
  - "451528"
  - "bf5f00"
  - "ecdae5"
  - "823857"
  - "ffff80"
  - "7792ac"
  - "898a49"
  - "373e68"
  - "dfffbf"
  - "a0ff40"
  - "fcfae1"
  - "ff00ff"
  - "82393c"
  - "b5d1d7"
  - "54466f"
  - "ddebe2"
  - "0060bf"
  - "007f7f"
  - "7f9757"
  - "acc6b5"
  - "40a0ff"
  - "bf005f"
  - "ff80bf"
  - "385376"
  - "7f007f"
  - "c080ff"
  - "8000ff"
  - "bfffdf"
  - "7fa37c"
  - "e6e6e6"
  - "dfbfff"
  - "bfbf00"
  - "80ffc0"
  - "ffff00"
  - "b27c51"
  - "ff4040"
  - "40ffff"
  - "f7dde9"
  - "434343"
  - "ff40ff"
  - "444f75"
  - "a94a76"
  - "9e8fa9"
  - "655a7f"
  - "ffffbf"
  - "8687a4"
dark_colors:
  - "d0d0d0"
  - "80ff00"
  - "bfdfff"
  - "ffbfff"
  - "ff9f40"
  - "80c0ff"
  - "ffdfbf"
  - "96bdc4"
  - "00ffff"
  - "e2f1f4"
  - "a2a2a2"
  - "c0a0b6"
  - "f8dddd"
  - "d8a5bb"
  - "e0dcaa"
  - "deebf6"
  - "ffff40"
  - "e1c4a8"
  - "a8bed1"
  - "ff0000"
  - "b7c296"
  - "ffc0c0"
  - "bfbfff"
  - "dcd1df"
  - "e6ebd5"
  - "ffbfdf"
  - "ffbf80"
  - "80ffff"
  - "fdeee0"
  - "c0ff80"
  - "00bfbf"
  - "d8a3a4"
  - "00ff80"
  - "bfffff"
  - "d2d1e1"
  - "40ffa0"
  - "ecdae5"
  - "ffff80"
  - "dfffbf"
  - "a0ff40"
  - "fcfae1"
  - "ff00ff"
  - "b5d1d7"
  - "ddebe2"
  - "ff80bf"
  - "bfffdf"
  - "e6e6e6"
  - "dfbfff"
  - "bfbf00"
  - "80ffc0"
  - "ffff00"
  - "40ffff"
  - "f7dde9"
  - "ffffbf"